[server]
maxUploadSize = 1000
maxMessageSize = 1000
# On force Streamlit à ne pas rafraîchir la page trop vite
runOnSave = false

[browser]
# Désactive la surveillance qui peut faire bugger l'upload massif
gatherUsageStats = false
