[server]
maxUploadSize = 1000
maxMessageSize = 1000
# On désactive les protections qui ralentissent le flux de données en direct
enableCORS = false
enableXsrfProtection = false

[browser]
# Permet au navigateur d'envoyer les fichiers plus vite
gatherUsageStats = false
